(() => {
  const stories = [
    {title:'Market Morning in the Highlands',place:'Dong Van · Local culture',image:'https://www.remotelands.com/travelogues/app/uploads/2015/01/HaGiang_8-1024x683.jpg',alt:'Local highland market and traditional clothing',intro:'A highland market is more than a place to shop: it is where neighbors meet, families trade the week’s harvest and handwoven clothing carries stories across generations.',body:['Arrive early, when the mountain air is cool and the market lanes begin to fill. Hmong, Dao, Tay and Nung families travel from nearby villages to exchange produce, tools, textiles and news. Each market has its own rhythm, shaped by the local weekly calendar.','Take time to notice the details: indigo cloth, embroidered collars, baskets of seasonal fruit and the food stalls serving a warm breakfast. Ask before photographing people, buy directly from local makers when you can, and let the visit unfold at the community’s pace.','Market days vary by village and season. Confirm the schedule with a local guide before setting out; a thoughtful visit is both more rewarding and more respectful.']},
    {title:'The Craft of a Highland Wardrobe',place:'Ha Giang · People & craft',image:'https://cdnphoto.dantri.com.vn/jeZO7pGLfcKrLCvpOuklCYggWPw%3D/thumb_w/1020/2022/12/04/20221105080555-1670143783290.jpg',alt:'Traditional garments and textiles at a Ha Giang market',intro:'Patterns, indigo dye and careful stitching make traditional clothing a living expression of identity in Vietnam’s northern mountains.',body:['Across Ha Giang, clothing traditions differ from one community to another. A jacket’s cut, a skirt’s pleats, a headscarf’s colors or a textile’s motifs can reflect local techniques passed from one generation to the next.','Some families still grow and process hemp, spin thread, dye cloth with indigo and embroider by hand. These are patient crafts, often practiced between farming seasons and family responsibilities. A market visit or community-run workshop can introduce the work without turning it into a performance.','Choose locally made pieces from artisans or cooperatives, ask how an item was made, and seek permission before photographing makers. Respectful curiosity helps keep the craft visible while honoring the people behind it.']},
    {title:'Following the Rice Terraces of Hoang Su Phi',place:'Hoang Su Phi · Landscapes',image:'https://thelooptours.com/upload/1081c0ec-aef1-4c7f-a56d-8e3a5d233dd9.jpg',alt:'Ha Giang mountain landscape and highland life',intro:'Layered fields trace the mountain slopes, changing from water mirrors to vivid green and then to harvest gold through the seasons.',body:['The terraces of Hoang Su Phi are a landscape shaped over generations. Narrow paths connect fields and villages, while water is guided down the slopes with care. The view changes dramatically with the agricultural calendar: reflective planting season, lush summer growth and golden harvest.','A local homestay makes it easier to walk at a gentle pace and learn how farming follows the terrain. Sunrise and late afternoon bring softer light, but weather in the mountains changes quickly, so leave room in your plan.','Stay on established paths, avoid stepping into planted fields and ask before entering private areas. Booking local guides and family-run accommodation keeps more of the journey’s value in the community.']},
    {title:'A Slow Day on the Ma Pi Leng Pass',place:'Meo Vac · Mountain roads',image:'https://cdnphoto.dantri.com.vn/SPHeG0xgZIfVFbx2pip8LjD3yyY%3D/thumb_w/1200/2021/07/01/207644897175849684504427969722800068904751n-1625130463593.jpg',alt:'Mountain pass in Ha Giang Vietnam',intro:'The road between Dong Van and Meo Vac rewards unhurried stops, careful driving and attention to the villages tucked into the karst landscape.',body:['Ma Pi Leng is known for steep limestone scenery and expansive views, but the experience is richer when the road is not treated as a race. Pause at safe viewpoints, watch the light move across the cliffs and give local traffic room on narrow bends.','Below the pass, the Nho Que River winds through Tu San Canyon. Boat departures and road conditions can vary, so confirm details locally and plan enough time for the descent and return.','Wear a helmet, travel with an experienced local driver if you are unfamiliar with mountain roads, and never stop in the roadway for a photograph. The best moments are worth waiting for a safe place.']},
    {title:'Staying a Little Longer in a Village',place:'Du Gia · Local stays',image:'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1200&q=85',alt:'Village scenery in northern Vietnam',intro:'A family-run homestay can turn a route through the mountains into a chance to share a meal and understand the everyday pace of village life.',body:['Choose a locally operated stay and ask what is included before booking. A shared dinner, a short walk or a conversation with your host can reveal more than a packed checklist of viewpoints.','Village customs differ. Follow your host’s guidance around household spaces, dress appropriately and ask before taking photos of people or homes. If you bring gifts, practical supplies arranged with the host are often more useful than distributing sweets to children.','Slow travel also means leaving space for weather, rest and spontaneous conversation. A flexible plan makes it easier to enjoy the place without putting pressure on the people who call it home.']}
  ];
  const init=()=>{
    const section=document.querySelector('#discover');
    const oldGrid=section?.querySelector('.discover-grid');
    if(!section||!oldGrid||section.dataset.blogReady)return;
    section.dataset.blogReady='true';
    const head=section.querySelector('.head');
    head.innerHTML='<div><div class="kicker">Stories from the road</div><h2>Journeys &amp; Stories</h2></div><p class="intro">Travel notes on highland places, local people and the traditions that make every journey meaningful.</p>';
    const wrapper=document.createElement('div');wrapper.className='travel-blog';
    wrapper.innerHTML='<div class="travel-blog-head"><div><div class="kicker">Places · people · culture</div><h2>Blog — Journeys</h2></div><div class="travel-blog-controls"><button class="travel-blog-arrow" type="button" aria-label="Previous stories">←</button><button class="travel-blog-arrow" type="button" aria-label="Next stories">→</button></div><p>Field notes and respectful travel ideas from the northern highlands.</p></div><div class="travel-blog-rail" tabindex="0" aria-label="Travel stories, scroll horizontally"></div>';
    const rail=wrapper.querySelector('.travel-blog-rail');
    stories.forEach((story,index)=>{const card=document.createElement('article');card.className='travel-article-card';card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label',`Read article: ${story.title}`);card.innerHTML=`<img src="${story.image}" alt="${story.alt}" loading="lazy"><div class="travel-article-copy"><span class="travel-article-meta">${story.place}</span><h3>${story.title}</h3><p>${story.intro}</p><span class="travel-article-read">Read story ↗</span></div>`;card.addEventListener('click',()=>open(story,card));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(story,card)}});rail.append(card)});
    oldGrid.replaceWith(wrapper);
    section.querySelector('.discover-button')?.remove();
    const modal=document.createElement('div');modal.className='blog-modal';modal.setAttribute('aria-hidden','true');modal.innerHTML='<article class="blog-modal-panel" role="dialog" aria-modal="true" aria-labelledby="blog-title" tabindex="-1"><button class="blog-modal-close" type="button" aria-label="Close article">×</button><div class="blog-modal-content"></div></article>';document.body.append(modal);
    const panel=modal.querySelector('.blog-modal-panel');let trigger=null;
    function open(story,card){trigger=card;modal.querySelector('.blog-modal-content').innerHTML=`<img src="${story.image}" alt="${story.alt}"><div class="blog-modal-copy"><div class="travel-article-meta">${story.place} · Travel journal</div><h2 id="blog-title">${story.title}</h2><p><strong>${story.intro}</strong></p>${story.body.map(p=>`<p>${p}</p>`).join('')}</div>`;modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');document.body.classList.add('blog-modal-open');requestAnimationFrame(()=>modal.querySelector('.blog-modal-close').focus({preventScroll:true}))}
    function close(){modal.classList.remove('is-open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('blog-modal-open');trigger?.focus({preventScroll:true})}
    modal.addEventListener('click',e=>{if(e.target===modal||e.target.closest('.blog-modal-close'))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('is-open'))close()});
    wrapper.querySelectorAll('.travel-blog-arrow').forEach((button,i)=>button.addEventListener('click',()=>rail.scrollBy({left:(rail.clientWidth+18)*(i?1:-1),behavior:'smooth'})));
  };
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
